### ISSUE TITLE
Inline dice rolls in chat appear as fully black

### ISSUE THREAD

**Issue by Sanyella** [Sanyella/FVTT-Custom-Journal-Theming#17]
![image](https://user-images.githubusercontent.com/50803386/90200484-fc45da00-dda5-11ea-9d5e-6dbc68664c7d.png)

This is odd, as I thought everything was cleanly targetted to only affect journals, but clearly there is something else at work here.

After some testing, it seems to always happen when Custom Journal is the only module, but not always when some other modules are activated. More testing is needed to see which one(s) is/are potentially "fixing" the issue.

**Comment by LarkinOmega** [comment]
Here is my list of enabled mods. None of these "fix" the issue, inline rolls were still showing up black 24 hours ago.

encounter-builder--v0.2.2;
spell-school-icons--v0.9.1;
resourcesplus--v1.5.5;
actually-private-rolls--v0.2;
adventuremusic--v1.0;
ambientdoors--v2.0.2;
animated-spell-effects--v0.2.1;
arms-reach--v1.1.1;
better-rolltables--v1.5.0;
betterrolls5e--v1.1.9;
bullseye--v1.0.3;
chat-images--v1.1.3;
chat-indicators--v1.0.0;
ChatPortrait--v0.1.4;
chat-scrolling--v0.0.7;
combat-enhancements--v0.1.2;
combatready--v1.1.8;
ct-effect-tooltips--v1.0.0;
combat-utility-belt--v1.1.3;
compendium-folders--v1.0.0;
conditions5e--v0.4.5.7;
cozy-player--v1.3.1;
cursor-zoom--v1.0.0-compatible-with-0.6.5;
DancingLights--v2.1.5;
daynightlights--v1.0.3;
dndAudioBundle-HammerHome--v1.0;
deselection--v1.4.4;
dice-calculator--v0.5.10;
dww-battlemaps--v1.0.0;
foundry-drmapzo-free--v0.10.0;
dynamiceffects--v0.5.94;
dynamic-illumination--v0.3.3;
ec-maps-remake-by-lios--v2.0.0;
find-the-culprit--v1.0.0;
followme--v1.0.0;
forien-quest-log--v0.4.4;
forien-unidentified-items--v0.2.3;
foundry_community_tables--v0.6;
workshop-welcome-screen--v1.0.3;
fpsmeter--v1.0.0;
gAudioBundle-1--v2.1;
gAudioBundle-2--v2.2;
gAudioBundle-3--v2.1;
gAudioBundle-4--v2.2;
token-drag-visibility--v1.1.1;
scaleGrid--v0.0.12;
grouproll--v0.6.3;
healthEstimate--v1.3.3;
inventory-plus--v0.2;
itemcollection--v1.3.15;
lazymoney--v0.9.7;
lessfog--v0.6.2;
lmrtfy--v1.2.2;
lib-wrapper--v1.0.1;
look-at-that--v0.0.1;
lootsheetnpc5e--v2.0.8;
magicitems--v1.18;
mergewalls--v0.0.11;
mess--v0.11.2;
michaelghelfi--v1.0;
miskasmaps--v1.0;
mountup--v3.0.1;
multilevel-tokens--v0.3.0;
mwpm--v0.4.0;
music-d20-sampler--v1.0.0;
navbar-tweaks--v1.0.3;
no-summon-vision--v1.0.0;
npcgen--v0.0.14;
tomcartos-ostenwold--v1.0.0;
permission_viewer--v0.7;
pick-up-stix--v0.7.9;
polyglot--v1.1;
popout--v0.8;
quicksceneview--v0.0.2;
response-times--v0.2.5;
right-click-enabler--v0.0.1;
sailors-funkyseas--v0.8.98;
smip-compendium--v0.3.0;
searchanywhere--v2.0.4;
ShowDragDistance--v1.0.9;
foundryvtt-show-notes--v0.1;
simplefog--v0.1.6;
skill-customization-5e--v2.1.0;
spellarena--v1.1.0;
furnace--v2.2;
mad-caverns-free--v1.0;
tidy-ui_game-settings--v0.1.15;
tidy5e-sheet--v0.2.17;
token-action-hud--v0.5.24;
token-auras--v1.4;
token-chat-link--v1.0.8;
token-info-icons--v1.1.5;
token-mold--v2.7.1;
trigger-happy--v0.7;
turnAlert--v1.4.0;
turnmarker--v2.6.9;
vtta-iconizer--v2.1.12;
vtta-party--v2.2.3;
vtta-tokenizer--v2.2.1;
wall-height--v2.0.1;

**Comment by Sanyella** [comment]
Hmm, that is odd. I forgot to mark this as closed, but I am rather certain I fixed exactly what was causing this (had a misplaced CSS rule that was the obvious culprit, once noticed). As for the other modules "fixing" it, I've mostly come to believe it was actually some caching issue or something of the sort, since the very same setup eventually came out as black as well. So just to make sure, have you updated and tried to refresh without caching (ctrl + f5)?
I won't close the issue just yet, in case this is still a problem, but I would be really surprised if it was. Thanks for the full report there!

**Comment by LarkinOmega** [comment]
It is working correctly now. Glad you found and fixed the issue so quickly (before I even reported), I am looking forward to using this module!

**Comment by Sanyella** [comment]
Awesome! Sorry for the initial bug, hope it didn't cause too much trouble on your end, and glad you're interested in my module! :) I'll properly close this issue now :P
