### ISSUE TITLE
Full compatibility of Darkslate and Royal themes with Polyglot

### ISSUE THREAD

**Issue by elizeuangelo** [Sanyella/FVTT-Custom-Journal-Theming#20]
Polyglot's runes are barely readable and not visually appeasing in Darkslate and Royal themes.

Maybe change/remove the background in polyglot's class when in these themes?

**Comment by Sanyella** [comment]
Hmm, good point! Hadn't actually noticed there was a background behind the runes, I'll admit I did a fairly tiny amount of testing regarding Polyglot in Journals, so sorry for the oversight! Not sure if that should be changed on my end, or on Polyglot's side though. Definitely going to look into that and try to figure out the best way to go about it!
