### ISSUE TITLE
Creating New Journal Entry

### ISSUE THREAD

**Issue by Gamaken53** [Sanyella/FVTT-Custom-Journal-Theming#24]
When creating a new journal entry, clicking on the edit button (to enter text) does not do anything.  The tool bar does not populate and cannot add text into the body.  Disabling module brings back functionality.

**Comment by Sanyella** [comment]
Yeah, that has been reported to me in Discord, I'm pretty sure I already know how to fix it, but do I can't for the time being. I'll try to fix that ASAP, in the meantime you can either roll back to the 1.0.6 version, or try adding `if (!editorOptions.style_formats) editorOptions.style_formats = {};` just under the console.log around line 20 in the js file, that *should* fix it, though no garanties as I could test it.

**Comment by Gamaken53** [comment]
> Yeah, that has been reported to me in Discord, I'm pretty sure I already know how to fix it, but do I can't for the time being. I'll try to fix that ASAP, in the meantime you can either roll back to the 1.0.6 version, or try adding `if (!editorOptions.style_formats) editorOptions.style_formats = {};` just under the console.log around line 20 in the js file, that _should_ fix it, though no garanties as I could test it.

no worries.  Just trying to help out by reporting.

**Comment by Sanyella** [comment]
Appreciated :)
