### ISSUE TITLE
Loses "secret" formatting

### ISSUE THREAD

**Issue by D20Chemist** [Sanyella/FVTT-Custom-Journal-Theming#27]
When active the paragraph custom option of "secret" for making GM only lines in the journal disappears and is replaced by all the Custom journal formatting options

**Comment by Sanyella** [comment]
Good catch! I'll look at fixing that, thanks for the report! I had missed, since it seems Polyglot re-adds the Custom->Secret menu, if that can help really short term :)

**Comment by Sanyella** [comment]
Forgot to close this, but this should now be fixed since yesterday's release. Happy secrets!
