### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [Sanyella/FVTT-Custom-Journal-Theming#34]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by Sanyella** [comment]
I'll definitely have to check how to do that exactly, and what can actually be translated. The styles certainly can, the sheet names I'm not so sure, but I'll look into that and keep you posted!

**Comment by lozalojo** [comment]
Great!

**Comment by Sanyella** [comment]
Translation support is in! For now, the actual sheet names can't be translated, but when the 7.x core update series becomes stable, I should be able to make use of the labels to make them translatable as well. Do not hesitate to make a pull request for any translation now, as well as letting me know if I missed anything! :)

**Comment by lozalojo** [comment]
Thank you, I translate the module to spanish. I will PR soon

**Comment by lozalojo** [comment]
Sent a PR, thanks!
